fix
GBLodb/requiousfrakto-ch-wiki pull request #3
Opened 2022-08-16 01:54 UTC by cneicy

machine -> machineContainer
and fix match

2022-08-16 02:26 UTC, cneicy commented
导包还缺点，有必要的话我补上。

2022-08-22 09:43 UTC, XHL315 requested changes

2022-08-22 09:43 UTC, XHL315 commented on advanced/world-require.md
>      var world as IWorld = machineContainer.world;
IWorld 的导包

2022-08-22 09:43 UTC, XHL315 commented on advanced/world-require.md
>      var pos as IBlockPos = machineContainer.pos;
IBlockPos 的导包

2022-08-22 09:57 UTC, cneicy commented on advanced/world-require.md
>      var pos as IBlockPos = machineContainer.pos;
完成

2022-08-22 09:57 UTC, cneicy commented on advanced/world-require.md
>      var world as IWorld = machineContainer.world;
完成

2022-08-22 09:59 UTC, XHL315 approved these changes

2022-08-22 17:04 UTC, merged